spring:
  application:
    name: notification-service
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: groupId
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring:
          kafka:
            consumer:
              value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
              properties:
                spring:
                  kafka:
                    consumer:
                      properties:
                        spring.kafka.consumer.value-deserializer.trusted.packages: "com.bhoper.model"
  mail:
    host: smtp.gmail.com
    port: 587
    username: solianik123456@gmail.com
    password: sxji jewo cvfx mqbt
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
server:
  port: 0