server:
  port: 8181

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes[0]:
        id: booking-management-service
        uri: lb:http://booking-management-service
        predicates[0]: Path=/api/bookings/**
      routes[1]:
        id: room-management-service
        uri: lb:http://room-management-service
        predicates[0]: Path=/api/rooms/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true